### ISSUE TITLE
`machinery build` fails with `write permission denied`

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1189]
```
machinery build sles11 --image-dir /tmp/image
root's password:
Jul-31 10:58:17 <1> : Setting log file to: /tmp/machinery-image20150731-13821-lc4qo5/kiwi-terminal-output.log
Jul-31 10:58:17 <1> : Destination: /tmp/machinery-image20150731-13821-lc4qo5/build doesn't exist
print() on closed filehandle GEN80 at /usr/share/kiwi/modules/KIWILog.pm line 470.
print() on closed filehandle GEN135 at /usr/share/kiwi/modules/KIWILog.pm line 470.
print() on closed filehandle GEN179 at /usr/share/kiwi/modules/KIWILog.pm line 470.
print() on closed filehandle GEN309 at /usr/share/kiwi/modules/KIWILog.pm line 470.
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/lib/build_task.rb:97:in `write': Permission denied @ rb_sysopen - /tmp/image/machinery.meta (Errno::EACCES)
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/lib/build_task.rb:97:in `build'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/lib/cli.rb:295:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1/bin/machinery:28:in `<top (required)>'
        from /usr/bin/machinery:24:in `load'
        from /usr/bin/machinery:24:in `<main>'
```

The directory `/tmp/image` belongs to user `root`: 
```
ls -ld /tmp/image
drwxr-xr-x 3 root root 4096 Jul 31 11:02 /tmp/image
```

**Comment by vwallfahrer** [comment]
We can not reproduce it.
