### ISSUE TITLE
Error while inspecting and editing a file in vim at the same time

### ISSUE THREAD

**Issue by mauromorales** [SUSE/machinery#1216]
I came up with this error while running an inspection and editing a file at the same time with vim, which by default creates swap files (e.g. `/etc/.my.cnf.swp`)

```
Inspecting unmanaged-files...
Note: Using traditional inspection because there is no helper binary for architecture 'x86_64' available.
 -> Found 1802 files and trees...Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh root@x.x.x.x LC_ALL\=C tar --create --gzip --null --files-from\\\=- --exclude /sys --exclude /proc --exclude /dev --exclude /dev/shm --exclude /run --exclude /sys/fs/cgroup" failed with status 2: tar: Removing leading `/' from member names (...).

Error output:
tar: Removing leading `/' from member names
tar: /etc/.my.cnf.swp: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

Backtrace:
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/home/mamorales/Projects/machinery/lib/logged_cheetah.rb:24:in `block in run'
/home/mamorales/Projects/machinery/lib/helper.rb:61:in `with_env'
/home/mamorales/Projects/machinery/lib/helper.rb:51:in `with_c_locale'
/home/mamorales/Projects/machinery/lib/logged_cheetah.rb:23:in `run'
/home/mamorales/Projects/machinery/lib/remote_system.rb:77:in `run_command'
/home/mamorales/Projects/machinery/lib/system.rb:63:in `create_archive'
/home/mamorales/Projects/machinery/lib/scope_file_access_archive.rb:4:in `retrieve_files_from_system_as_archive'
/home/mamorales/Projects/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:408:in `run_extraction'
/home/mamorales/Projects/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:392:in `run_inspection'
/home/mamorales/Projects/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:249:in `inspect'
/home/mamorales/Projects/machinery/lib/inspect_task.rb:86:in `block in build_description'
/home/mamorales/Projects/machinery/lib/inspect_task.rb:78:in `each'
/home/mamorales/Projects/machinery/lib/inspect_task.rb:78:in `build_description'
/home/mamorales/Projects/machinery/lib/inspect_task.rb:23:in `inspect_system'
/home/mamorales/Projects/machinery/lib/cli.rb:539:in `block (2 levels) in <class:Cli>'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
/suse/mamorales/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
bin/machinery:28:in `<main>'
````

**Comment by keberle94** [comment]
Sorry, but I could not reproduce this error. I opened the same file with vi and was running both inspection types, with and without the machinery-helper. The result could be also seen [here](http://pastebin.suse.de/15177)

**Comment by thardeck** [comment]
The most likely reason why the issue appeared is that the swp file was there during find inspection but when it tried to extract it vi was closed or a new file was opened so the swp file wasn't there anymore.

**Comment by mauromorales** [comment]
That makes sense and I'll close the issue then.

**Comment by thardeck** [comment]
Most likely related to #1253.

**Comment by cornelius** [comment]
#2188 will fix this
