### ISSUE TITLE
`machinery containerize` raises an unexpected error if the output directory does not exist

### ISSUE THREAD

**Issue by vwallfahrer** [SUSE/machinery#1239]
```
gmachinery containerize refsys -o /tmp/bla
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/home/vwallfahrer/alfred/machinery/lib/workload_mapper.rb:23:in `write': No such file or directory @ rb_sysopen - /tmp/bla/docker-compose.yml (Errno::ENOENT)
	from /home/vwallfahrer/alfred/machinery/lib/workload_mapper.rb:23:in `write_compose_file'
	from /home/vwallfahrer/alfred/machinery/lib/containerize_task.rb:22:in `containerize'
	from /home/vwallfahrer/alfred/machinery/lib/cli.rb:805:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
	from /home/vwallfahrer/alfred/machinery/bin/machinery:28:in `<main>'
```

**Comment by mauromorales** [comment]
Closing as it seems we've taken care of it already

    $ bin/machinery containerize refsys --output-dir=/tmp/blah
    Detected workload 'mariadb'.
    Detected workload 'docker-registry'.
    Detected workload 'rails'.
    
    Wrote to /tmp/blah/refsys.
