### ISSUE TITLE
setup.rb in containerize dir fails

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1307]
When running the setup.rb script in a directory created by the containerize command, it just exists with the following error:

--------------------------------snip-----------------------------------
chuller@lagrange:/tmp/10.162.168.67/10.162.168.67> ./setup.rb
/usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- docker (LoadError)
        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./setup.rb:18:in `<main>'
--------------------------------snip-----------------------------------

indicating that it needs the docker gem, I installed that gem as well as the docker-api gem as told by Mauro.
This however only changed the error message that appears when setup.rb exits:

----------------------------------snip--------------------------------------
chuller@lagrange:/tmp/10.162.168.67/10.162.168.67> ./setup.rb
Setting up mariadb
Building image 10.162.168.67_db
./setup.rb:37:in `build_image': uninitialized constant Docker::Image (NameError)
        from ./setup.rb:51:in `<main>'
----------------------------------snip--------------------------------------

gems installed:

---------------------------------snip----------------------------------
chuller@lagrange:/tmp/10.162.168.67/10.162.168.67> gem list docker
 
*** LOCAL GEMS ***
 
docker (0.0.1)
docker-api (1.22.4)
---------------------------------snip----------------------------------

**Comment by greygoo** [comment]
Removing the docker gem and only keeping the docker-api gem fixes the problem, after that setup.rb does run.

We need to add a clear instruction to only install the docker-api gem as the "require 'docker'" statement in the setup.rb code might make people try to install the docker gem which then prevents setup from working.
