### ISSUE TITLE
after running setup.rb, docker-compose fails with a permission denied error

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1312]
after setup.rb ran successfully, using docker-compose to start the containerized system fails with a permission denied:

-------------snip-----------
<removed excessive output from setup.rb>

== 20150729153854 AddEnabledToUsers: migrating ================================
-- add_column(:users, :enabled, :bool, {:default=>true})
   -> 0.3832s
== 20150729153854 AddEnabledToUsers: migrated (0.3833s) =======================

Stopping db service
removing containers
chuller@lagrange:/data/big/chuller/docker/tests/container_tests_portus> docker-compose up
Building db...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 32, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 471, in up
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 245, in up
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 318, in execute_convergence_plan
    do_build=do_build,
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 212, in create_container
    insecure_registry=insecure_registry,
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 239, in ensure_image_exists
    self.build()
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 653, in build
    dockerfile=self.options.get('dockerfile', None),
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 101, in build
    context = utils.tar(path, exclude=exclude)
  File "/usr/lib/python2.7/site-packages/docker/utils/utils.py", line 91, in tar
    t.add(os.path.join(path, arcname), arcname=arcname)
  File "/usr/lib64/python2.7/tarfile.py", line 1994, in add
    with bltn_open(name, "rb") as f:
IOError: [Errno 13] Permission denied: '/data/big/chuller/docker/tests/container_tests_portus/mariadb/data/aria_log.00000001'
------------------snip----------------------

**Comment by greygoo** [comment]
seems the file in question is created with wrong owner:

chuller@lagrange:/data/big/chuller/docker/tests/container_tests_portus> ll /data/big/chuller/docker/tests/container_tests_portus/mariadb/data/aria_log.00000001 
-rw-rw---- 1 mysql ntp 16384 Sep  9 11:55 /data/big/chuller/docker/tests/container_tests_portus/mariadb/data/aria_log.00000001

**Comment by mauromorales** [comment]
could not reproduce in a completely clean environment, let's look at it together

**Comment by greygoo** [comment]
the propblem seems to occur if there is an inconsistency of the ID's for groups inside the docker container and the external system. In my case the mysql group had differing IDs on both systems, triggering the problem.

**Comment by mauromorales** [comment]
everything inside `mariadb/data` will get assigned the user mysql(60) and group mysql(496) ... which in the host don't necessarily exist or are the same

**Comment by greygoo** [comment]
Really weird - after once running setup.rb as root, the problem is not reproducable here as well. Even with new containerization into a fresh directory

**Comment by greygoo** [comment]
my suggestion would be to require setup.rb being run as root and then compose-up is run as normal user, that seems to work around the problem. Could you add that to the README?

**Comment by mauromorales** [comment]
will do

**Comment by mauromorales** [comment]
did some research and it seems to me that allowing the container to keep it's uid:gid is the way to go with this one even if it doesn't match with the host machine. Here is a post from the MariaDB Enterprise where they just add the extra step of finding out which uid:gid are these before creating the folder on the host. On our case we don't need this since we are creating the database from scratch.

https://mariadb.com/kb/en/mariadb-enterprise/mariadb-enterprise-in-docker/
