### ISSUE TITLE
inspecting busybox docker container fails

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1435]
busybox is the second top container on docker hub today and inspecting it fails with th following output:

--------------------------snip-------------------------
chuller@lagrange:/data/big/chuller/machinery-helper(master)> machinery inspect-container -x --docker busybox
Inspecting busybox for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...
 
Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)
 
 
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "docker rm -f ''" failed with status 1: /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of nil into String (TypeError) (...).
 
Error output:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of nil into String (TypeError)
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `block in fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:471:in `fork_commands'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:359:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/logged_cheetah.rb:23:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/docker_system.rb:36:in `stop'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/cli.rb:653:in `ensure in block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/cli.rb:653:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bin/machinery:28:in `<top (required)>'
        from /usr/bin/machinery:24:in `load'
        from /usr/bin/machinery:24:in `<main>'
 
Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/docker_system.rb:36:in `stop'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/cli.rb:653:in `ensure in block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/lib/cli.rb:653:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151001T153218ZopenSUSE132gitb0f178f/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
--------------------------snip-------------------------

**Comment by greygoo** [comment]
not a rpm based container, so, no blocker for the feature. Will leave it open as we should handle the problem more gracefully.
