### ISSUE TITLE
Inspecting a container created with containerize fails

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1440]
After contanerizing the a wordpress system I get a web and a db container. when inspecting the db container, this fails with the following output:

-------------------------------------snip-------------------------------------------
chuller@lagrange:/data/big/chuller/machinery(master)> machinery inspect-container -x --docker 10.162.168.223_db
Inspecting 10.162.168.223_db for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...
 
Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)
 
 
Inspecting os...
 -> Found operating system 'openSUSE 13.2 (Harlequin)' version '13.2 (Harlequin)'.
Inspecting packages...
 -> Found 135 packages.
Inspecting patterns...
 -> Found 0 patterns.
Inspecting repositories...
 -> Found 4 repositories.
Inspecting users...
 -> Found 14 users.
Inspecting groups...
 -> Found 36 groups.
Inspecting services...
 -> Found 0 services.
Inspecting config-files...
 -> Extracted 6 changed configuration files.
Inspecting changed-managed-files...
 -> Extracted 430 changed files.
Inspecting unmanaged-files...
 -> Extracted 56 files and treesMachinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "tar tvf /suse/chuller/.machinery/10.162.168.223_db/unmanaged_files.tmp/files.tgz" failed with status 2:  (...).
 
Error output:
 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 
Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/tarball.rb:25:in `list'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/plugins/unmanaged_files/unmanaged_files_inspector.rb:104:in `block in extract_tar_metadata'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/plugins/unmanaged_files/unmanaged_files_inspector.rb:103:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/plugins/unmanaged_files/unmanaged_files_inspector.rb:103:in `extract_tar_metadata'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/plugins/unmanaged_files/unmanaged_files_inspector.rb:287:in `run_helper_inspection'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/plugins/unmanaged_files/unmanaged_files_inspector.rb:240:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/inspect_task.rb:87:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/inspect_task.rb:79:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/inspect_task.rb:79:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/inspect_task.rb:21:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/lib/cli.rb:643:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.13.0.20151002T135022ZopenSUSE132giteb0164f/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
 
chuller@lagrange:/data/big/chuller/machinery(master)>
-------------------------------------snip-------------------------------------------

**Comment by greygoo** [comment]
machinery-helper was probably not the latest version, i made sure i copy the latest version and now the problem vanished.
