### ISSUE TITLE
Invalid characters in manifest.json Make Machinery Crash

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1586]
System descriptions containing `/etc/umlaut-??????.conf` from `test-quote-char-and-umlauts-1.0-10.1.noarch` in the config-files section make machinery crash on SLES12.

[manifest.json.txt](https://github.com/SUSE/machinery/files/25246/manifest.json.txt)

```
boothuser@linux:~> echo $LANG
C
boothuser@linux:~> machinery -v
machinery version 1.14.2 (system description format version 5)
boothuser@linux:~> machinery show devel
Machinery experienced an unexpected error.
If this impacts your business please file a service request at https://www.suse.com/mysupport
so that we can assist you on this issue. An active support contract is required.
/usr/lib64/ruby/2.1.0/json/common.rb:155:in `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /usr/lib64/ruby/2.1.0/json/common.rb:155:in `initialize'
        from /usr/lib64/ruby/2.1.0/json/common.rb:155:in `new'
        from /usr/lib64/ruby/2.1.0/json/common.rb:155:in `parse'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/manifest.rb:69:in `parse'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/manifest.rb:40:in `initialize'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/manifest.rb:32:in `new'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/manifest.rb:32:in `load'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/system_description.rb:64:in `load'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/cli.rb:769:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bin/machinery:34:in `<top (required)>'
        from /usr/bin/machinery:24:in `load'
        from /usr/bin/machinery:24:in `<main>' 
```

**Comment by tgoettlicher** [comment]
It happens with machinery version 1.14.2 if I remember correctly.

**Comment by mauromorales** [comment]
Issue isn't there in 1.18.0 anymore, closing.
