### ISSUE TITLE
Docker: Permission denied exception

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1597]
I found an issue while I tried to inspect a container. I didn't run the command as root user. We should catch the exception and print a better error message.

```
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "docker images" failed with status 1: Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: permission denied. (...).

Error output:
Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: permission denied.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/lib/docker_system.rb:127:in `validate_image_name'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/lib/docker_system.rb:28:in `initialize'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/lib/cli.rb:635:in `new'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/lib/cli.rb:635:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:309:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:83:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.15.0/bin/machinery:34:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
```

**Comment by mauromorales** [comment]
@mschnitzer check `systemctl status docker` is it running? Also make sure your was added to the `docker` group

**Comment by mschnitzer** [comment]
Docker was running and my user is not in the `docker` group. I know that my user has to be in that group but I wanted if Machinery crashes in some way :-D

**Comment by fschueller** [comment]
Is this still an issue? I cannot reproduce the error. 
When inspecting a container with ```docker``` running and my user not in the ```docker``` group, it only throws me the following: 

```Unknown docker image: '13_2_docker```

Is this the desired behaviour?
