### ISSUE TITLE
`machinery list` fails because of uninstalled go-package

### ISSUE THREAD

**Issue by vwallfahrer** [SUSE/machinery#1605]
I tried to run `machinery list` and got that error: 

```
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors': Execution of "rake build" failed with status 1: Warning: The Go compiler is not available on this system. Skipping building the machinery-helper. (...). (Cheetah::ExecutionFailed)
	from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
	from /home/vwallfahrer/alfred/machinery/bin/machinery:25:in `block in <main>'
	from /home/vwallfahrer/alfred/machinery/bin/machinery:24:in `chdir'
	from /home/vwallfahrer/alfred/machinery/bin/machinery:24:in `<main>'
```

But instead it should only show a warning if go is missing.

**Comment by mschnitzer** [comment]
Try to install `zypper in go`
