### ISSUE TITLE
Machinery experienced an unexpected error

### ISSUE THREAD

**Issue by matwey** [SUSE/machinery#1609]
Hello, I've faced unexpected error and machinery 1.14.1 (and 1.16.0) asked me to fill the issue.

```
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh matwey@192.168.10.7 -o LogLevel\=ERROR LC_ALL\=en_US.utf8 stat --printf \\\%a:\\\%U:\\\%G:\\\%u:\\\%g:\\\%F:\\\%n\\\\n /etc/ssh/sshd_config /etc/pam.d/common-account /etc/pam.d/common-auth /etc/pam.d/common-password /etc/pam.d/common-session /etc/influxdb/config.toml /etc/sudoers /etc/django-eagle/local_settings.py /etc/lighttpd/vhosts.d/django-eagle.conf /etc/collectd.conf /etc/logrotate.d/syslog /etc/ntp.conf /etc/lighttpd/lighttpd.conf /etc/lighttpd/modules.conf /etc/sysconfig/SuSEfirewall2 /etc/default/grub /etc/systemd/journald.conf /etc/syslog-ng/syslog-ng.conf" failed with status 1: stat: cannot stat ‘/etc/lighttpd/vhosts.d/django-eagle.conf’: Permission denied (...).

Error output:
stat: cannot stat ‘/etc/lighttpd/vhosts.d/django-eagle.conf’: Permission denied
stat: cannot stat ‘/etc/lighttpd/lighttpd.conf’: Permission denied
stat: cannot stat ‘/etc/lighttpd/modules.conf’: Permission denied

Standard output:
640:root:root:0:0:regular file:/etc/ssh/sshd_config
777:root:root:0:0:symbolic link:/etc/pam.d/common-account
777:root:root:0:0:symbolic link:/etc/pam.d/common-auth
777:root:root:0:0:symbolic link:/etc/pam.d/common-password
777:root:root:0:0:symbolic link:/etc/pam.d/common-session
644:root:root:0:0:regular file:/etc/influxdb/config.toml
440:root:root:0:0:regular file:/etc/sudoers
644:root:root:0:0:regular file:/etc/django-eagle/local_settings.py
640:root:root:0:0:regular file:/etc/collectd.conf
644:root:root:0:0:regular file:/etc/logrotate.d/syslog
640:root:ntp:0:493:regular file:/etc/ntp.conf
644:root:root:0:0:regular file:/etc/sysconfig/SuSEfirewall2
644:root:root:0:0:regular file:/etc/default/grub
644:root:root:0:0:regular file:/etc/systemd/journald.conf
644:root:root:0:0:regular file:/etc/syslog-ng/syslog-ng.conf


Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/remote_system.rb:84:in `run_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/changed_rpm_files_helper.rb:108:in `get_file_properties'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/changed_rpm_files_helper.rb:139:in `get_path_data'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/plugins/config_files/config_files_inspector.rb:99:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/inspect_task.rb:87:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/inspect_task.rb:79:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/inspect_task.rb:79:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/inspect_task.rb:21:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/lib/cli.rb:600:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bundle/ruby/2.1.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/bin/machinery:34:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'```

**Comment by mschnitzer** [comment]
@matwey does your user `matwey' has root privileges on the remote machine? That's really important.

**Comment by matwey** [comment]
Hello,

user `matwey' is in sudoers as required in man page
```
matwey ALL=(ALL) NOPASSWD: /usr/bin/find,/usr/bin/cat,/bin/cat,/usr/bin/rsync,/bin/rpm -Va *,/bin/tar --create *
```

Probably ```stat``` call should be wrapped into ```sudo``` also.

**Comment by mschnitzer** [comment]
OK, I'll do some tests and then I'll ping you again.

**Comment by mschnitzer** [comment]
@matwey could you please give me a bit more information:
* Which distribution do you use?
* Which distribution does the remote system has?

**Comment by matwey** [comment]
* I use openSUSE Leap 42.1
* openSUSE 13.2 is on the remote system
* The command is ```machinery inspect --verbose --remote-user matwey 192.168.10.7```

**Comment by mschnitzer** [comment]
Which permissions does these files have?
```
stat: cannot stat ‘/etc/lighttpd/vhosts.d/django-eagle.conf’: Permission denied
stat: cannot stat ‘/etc/lighttpd/lighttpd.conf’: Permission denied
stat: cannot stat ‘/etc/lighttpd/modules.conf’: Permission denied
```

**Comment by matwey** [comment]
```
drwxr-x--- 1 root lighttpd    78 Jul  4 00:18 /etc/lighttpd
-rw-r----- 1 root lighttpd 11739 Dec 13  2014 /etc/lighttpd/lighttpd.conf
-rw-r----- 1 root lighttpd  3233 Jul  4 00:18 /etc/lighttpd/modules.conf
drwxr-x--- 1 root lighttpd    64 Jul 17 20:32 /etc/lighttpd/vhosts.d
-rw-r--r-- 1 root root       520 Jul 17 20:32 /etc/lighttpd/vhosts.d/django-eagle.conf
```

**Comment by mschnitzer** [comment]
OK, there is currently no temporarily solution for you but I found the bug and the bug will be fixed in the next release. It doesn't help when you allow the user to execute the `stat` command in the /etc/sudoers file cause we don't call the `stat` command with sudo privileges in Machinery.
