### ISSUE TITLE
Unexpected error while using `build`

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1671]
I tried to reproduce issue #1667 and I got an exception when I was running `machinery build --image-dir test test`

Exception:
```
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/home/manuel/GitHub/machinery/lib/local_system.rb:97:in `validate_build_compatibility': undefined method `display_name' for nil:NilClass (NoMethodError)
	from /home/manuel/GitHub/machinery/lib/build_task.rb:21:in `build'
	from /home/manuel/GitHub/machinery/lib/cli.rb:334:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/app_support.rb:309:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/app_support.rb:309:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.3/lib/gli/app_support.rb:83:in `run'
	from /home/manuel/GitHub/machinery/bin/machinery:34:in `<main>'
```

**Comment by thardeck** [comment]
This is already fixed.
