### ISSUE TITLE
RHEL6 services inspection fails on ubuntu_integration branch

### ISSUE THREAD

**Issue by aduffeck** [SUSE/machinery#1806]
The new init system detection logic seems to fail for RHEL6, apparently initctl is available there as well:

```
Error output:
initctl: invalid command: show-config
Try `initctl --help' for more information.

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/remote_system.rb:84:in `run_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/plugins/services/services_inspector.rb:108:in `parse_ubuntu_upstart'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/plugins/services/services_inspector.rb:99:in `inspect_ubuntu_services'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/plugins/services/services_inspector.rb:39:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/inspect_task.rb:87:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/inspect_task.rb:79:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/inspect_task.rb:79:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/inspect_task.rb:21:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/lib/cli.rb:595:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.3.20160111T155502ZSLE12gitf3d3ee5/bin/machinery:33:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
```

**Comment by greygoo** [comment]
looking at /sbin/init --version on RHEL6 it shows that here in fact also upstart is used:

-------------------snip---------------------
system-config-authentication  system-config-firewall-tui    system-config-network         system-config-network-tui     systool                       
-bash-4.1# /sbin/init --version
init (upstart 0.6.5)
Copyright (C) 2010 Canonical Ltd.
-------------------snip---------------------

compared to Ubuntu:

-------------------snip---------------------
root@base-ubuntu-14:~# /sbin/init --version
init (upstart 1.12.1)
Copyright (C) 2006-2014 Canonical Ltd., 2011 Scott James Remnant

This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-------------------snip---------------------

So the real fix would be to adjust the upstart inspection to also cover RHEL6

**Comment by thardeck** [comment]
Fixed
