### ISSUE TITLE
inspection of ubuntu docker image fails

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1875]
Tried to inspect a ubuntu docker image, and it failed for the unmanaged file inspection.

chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery inspect-container ubuntu
Inspecting ubuntu for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'Ubuntu 14.04.3 LTS' version '14.04.3 LTS, Trusty Tahr'.
Inspecting packages...
 -> Found 184 packages.
Inspecting patterns...
 -> For a patterns inspection please install the package tasksel on the inspected system.
Inspecting repositories...
 -> Found 12 repositories.
Inspecting users...
 -> Found 20 users.
Inspecting groups...
 -> Found 43 groups.
Inspecting services...
 -> Found 0 services.
Inspecting config-files...
Warning: The list of changed config and managed files is not complete on dpkg systems. The reason for this is missing verifcation data: https://github.com/SUSE/machinery/wiki/Ubuntu-Inspection
 -> Found 0 changed configuration files.
Inspecting changed-managed-files...
 -> Found 1 changed files.
Inspecting unmanaged-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "docker exec --user\=root -i 03d1c207d6ac19a540337823b410bc6e810009b914a7ef033cc929fbfee8cfa7 \[\"btrfs\",\ \"subvolume\",\ \"list\",\ \"/\"\] \[\"awk\",\ \"\{print\ \$NF\}\"\]" failed with status 1: /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of Array into String (TypeError) (...).

Error output:
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of Array into String (TypeError)
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `block in fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork'
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork_commands_recursive'
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:471:in `fork_commands'
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:359:in `run'
        from /data/chuller/machinery/lib/logged_cheetah.rb:23:in `run'
        from /data/chuller/machinery/lib/docker_system.rb:44:in `run_command'
        from /data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:535:in `btrfs_subvolumes'
        from /data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:360:in `run_inspection'
        from /data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:275:in `inspect'
        from /data/chuller/machinery/lib/inspect_task.rb:87:in `block in build_description'
        from /data/chuller/machinery/lib/inspect_task.rb:79:in `each'
        from /data/chuller/machinery/lib/inspect_task.rb:79:in `build_description'
        from /data/chuller/machinery/lib/inspect_task.rb:21:in `inspect_system'
        from /data/chuller/machinery/lib/cli.rb:639:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
        from ./bin/machinery:33:in `<main>'

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/data/chuller/machinery/lib/logged_cheetah.rb:23:in `run'
/data/chuller/machinery/lib/docker_system.rb:44:in `run_command'
/data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:535:in `btrfs_subvolumes'
/data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:360:in `run_inspection'
/data/chuller/machinery/plugins/unmanaged_files/unmanaged_files_inspector.rb:275:in `inspect'
/data/chuller/machinery/lib/inspect_task.rb:87:in `block in build_description'
/data/chuller/machinery/lib/inspect_task.rb:79:in `each'
/data/chuller/machinery/lib/inspect_task.rb:79:in `build_description'
/data/chuller/machinery/lib/inspect_task.rb:21:in `inspect_system'
/data/chuller/machinery/lib/cli.rb:639:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
./bin/machinery:33:in `<main>'

**Comment by greygoo** [comment]
happnes as well on debian. Works on opensuse leap, so must be ubuntu related.
