### ISSUE TITLE
OS scop stores redundant data

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#1896]
At the moment our display_name for Unknown oses which is used in several places is put together like this:
` "#{name} #{version} (#{architecture})"`

The result for Ubuntu for example is:
`Ubuntu 14.04.3 LTS 14.04.3 LTS, Trusty Tahr (x86_64)`

Or Fedora 23 Server Edition:
`Fedora 23 (Server Edition) 23 (Server Edition) (x86_64)`

For all newer oses we parse the os-release. Instead of the PRETTY_NAME and VERSION we should use NAME and VERSION_ID. This will prevent redundancy and give a proper output unless we think that the variant_name is important.
### /etc/os-release:
```
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
```
NAME=Fedora
VERSION="23 (Server Edition)"
ID=fedora
VERSION_ID=23
PRETTY_NAME="Fedora 23 (Server Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:23"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=23
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=23
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Server Edition"
VARIANT_ID=server
```

If we would do this the output would look as follow:
`Ubuntu 14.04 (x86_64)`
`Fedora 23 (x86_64)`

If the variant is important we can continue using VERSION but still not the PRETTY_NAME.

`Ubuntu 14.04.3 LTS, Trusty Tahr (x86_64)`
`Fedora23 (Server Edition) (x86_64)`

**Comment by greygoo** [comment]
I agree with the suggestion, NAME and VERSION_ID are still explicit.

**Comment by thardeck** [comment]
There would be some penalties.

The name for SLES would be `SLES` instead of `SUSE Linux Enterprise server`. The `VERSION_ID` of Tumbleweed would be just the date. But of course this we could fix by additional logic which partly is already in place.

But of course we could use the general os-release approach for all of them.

**Comment by vladshablinsky** [comment]
HI, I'm Vlad. I'm new to Machinery and I picked this issue as a starting point. I found that `os_inspector.rb` is responsible for `PRETTY_NAME` and `VERSION`. So I changed them in `result` Hash and now some tests need to be changed. As I understood, not all the system's names and version are parsed from os-release, some of them hardcoded i.e. for openSUSE, correct me if I wrong.
I know, it's not how TDD works and maybe I needed to write tests and then change other things, but I'm not sure about all the systems present in tests. It would be great to have any guidance or help . Here is a diff of what I did (probably something ugly) (https://github.com/SUSE/machinery/compare/master...vladshablinsky:os_redundancy)

Thanks!

**Comment by thardeck** [comment]
Hi @vladshablinsky, thx for your work.

So all newer supported Linux distributions have an `os-release` file, but the olders only have a `suse-release` or `redhat-release` file which are structured differently than os-release.

The original files for the unit tests are stored under `spec/data/os/<OS_NAME>`. Since the output of the os inspector is also used for the integration tests the according files in the same directory also need to be changed.

But for developing I would mainly specify your desired changes under `spec/unit/os_inspector_spec.rb`, run the tests on it with rspec and then adapt the code in `os_inspector.rb`

At last I would change the integration tests.

**Comment by vladshablinsky** [comment]
@thardeck, I haven't changed anything in integration tests yet, here is what I have for now: 
https://github.com/SUSE/machinery/compare/master...vladshablinsky:os_redundancy

> The name for SLES would be SLES instead of SUSE Linux Enterprise server. The VERSION_ID of Tumbleweed would be just the date. But of course this we could fix by additional logic which partly is already in place.

What do I need to do with these cases? 
```ruby
Failures:

  1) OsInspector.inspect is able to recognize the rolling openSUSE release Tumbleweed
     Failure/Error: expect(inspector.summary).to include("openSUSE Tumbleweed")
       expected "Found operating system 'openSUSE' version '20150421'." to include "openSUSE Tumbleweed"
     # ./spec/unit/os_inspector_spec.rb:166:in `block (3 levels) in <top (required)>'

  2) OsInspector.inspect is able to recognize SLES11SP4
     Failure/Error: expect(inspector.summary).to include("SUSE Linux Enterprise Server 11")
       expected "Found operating system 'SLES' version '11.4'." to include "SUSE Linux Enterprise Server 11"
     # ./spec/unit/os_inspector_spec.rb:196:in `block (3 levels) in <top (required)>'

Finished in 0.13675 seconds (files took 0.54506 seconds to load)
17 examples, 2 failures

Failed examples:

rspec ./spec/unit/os_inspector_spec.rb:155 # OsInspector.inspect is able to recognize the rolling openSUSE release Tumbleweed
rspec ./spec/unit/os_inspector_spec.rb:185 # OsInspector.inspect is able to recognize SLES11SP4

```

Thanks!

**Comment by thardeck** [comment]
@vladshablinsky 
It tells you at the end were the test is located.
But I would not change the first test but the output since openSUSE with just a date might be recognizable for some but not in general. You will most likely need a static work around for that to add the Tumbleweed but having the date as version is good I think.

For the second Test I would also change the expected version to `11-SP4` which would be a similar structure to the one of SLES 12 with `12-SP1 `.
11.4 was never publicly visible for SLES11 and would look for most people like openSUSE 11.4.
I would add a method to convert the `11.x` version for SLES 11 to `11-SPx`

Then all the latest SLES versions would look similar.

**Comment by vladshablinsky** [comment]
@thardeck 

> For the second Test I would change the expected version to 11-SP4 which would be a similar structure to the one of SLES 12 with 12-SP1.

To `11-SP1` or to `11 SP1`? I don't know where I can find `os-release` with 12.1 or 12-SP1 or 12 SP1, it's just 12 everywhere in data files and, so I don't know the format.

> 11.4 was never publicly visible for SLES11 and would look for most people like openSUSE 11.4.
I would add a method to convert the 11.x version for SLES 11 to 11-SPx

What about something like this in `OsInspector#get_os_from_os_release` ?
```ruby
      # converts SLES11 SP4 result to SP3 style
      # the results are different because SP4 has an os-release
      if result["pretty_name"] =~ /^SUSE Linux Enterprise Server 11 (SP\d)$/
        result["pretty_name"] = "SUSE Linux Enterprise Server 11"
        result["version_id"] = "11 #{$1}"
      end
```

And how do I change this line? 

```ruby
expect(inspector.summary).to include("SUSE Linux Enterprise Server 11")
```

to reduce the failure? 
How about this?

```ruby
expect(inspector.summary).to include("SLES")
expect(inspector.summary).to include("11 SP1")
```

Now I have a failure:
```
expected "Found operating system 'SLES' version '11 SP4'." to include "SUSE Linux Enterprise Server 11"
```
