### ISSUE TITLE
Exporting the description of a docker image to kiwi fail with several issues

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1921]
Description:

I tried to export the description created from inspecting a docker container to kiwi. This triggered a backtrace and error message as the docker image has no init system:

------------------snip-----------------------
```
chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery export-kiwi --kiwi-dir /tmp/opensuse_container opensuse
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/data/chuller/machinery/lib/kiwi_config.rb:336:in `apply_services': Unsupported init system: "none". (RuntimeError)
        from /data/chuller/machinery/lib/kiwi_config.rb:223:in `block (2 levels) in generate_config'
        from /usr/lib64/ruby/gems/2.1.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/builder.rb:391:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/builder.rb:391:in `insert'
        from /usr/lib64/ruby/gems/2.1.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
        from /data/chuller/machinery/lib/kiwi_config.rb:196:in `block in generate_config'
        from /usr/lib64/ruby/gems/2.1.0/gems/nokogiri-1.6.7.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
        from /data/chuller/machinery/lib/kiwi_config.rb:195:in `new'
        from /data/chuller/machinery/lib/kiwi_config.rb:195:in `generate_config'
        from /data/chuller/machinery/lib/kiwi_config.rb:35:in `initialize'
        from /data/chuller/machinery/lib/cli.rb:472:in `new'
        from /data/chuller/machinery/lib/cli.rb:472:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
        from ./bin/machinery:33:in `<main>'
```
------------------snip-----------------------

**Comment by greygoo** [comment]
When exchanging the "none" for the init system entry in the manifest it is possible to export a kiwi config.

However, when attempting to build a image using this config another problem occurs:

----------------------snip----------------------
chuller@lagrange:/tmp/opensuse_container/opensuse-kiwi> sudo /usr/sbin/kiwi --build /tmp/opensuse_container/opensuse-kiwi --destdir /tmp/kiwi
Jan-29 12:00:36 <1> : Destination: /tmp/kiwi/build doesn't exist
Jan-29 12:00:36 <1> : --> Creating directory: /tmp/kiwi/build                                                                                                                                                                       done
Jan-29 12:00:36 <1> : Description provides no MD5 hash, check
Jan-29 12:00:36 <1> : Reading image description [Prepare]...
Jan-29 12:00:36 <3> : Selected bootloader is grub2, but the required package(s) grub2 grub2-x86_64-efi are not included in the image.                                                                                               failed
Jan-29 12:00:36 <1> : Closing session with ecode: 1
Jan-29 12:00:36 <3> : KIWI exited with error(s)
----------------------snip----------------------

**Comment by greygoo** [comment]
Another issue occurs on the package installation, the docker container contains a package called "openSUSE-release-mini" which is not found in the repos, causing kiwi to exit with an error:

----------------------snip------------------------
```
+ /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/kiwi/build/image-root//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/kiwi/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/kiwi/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.20912 --no-gpg-checks --root /tmp/kiwi/build/image-root install --auto-agree-with-licenses --no-recommends acl bash bzip2 ca-certificates coreutils cpio cracklib cracklib-dict-small device-mapper diffutils dirmngr elfutils expat file file-magic filesystem fillup findutils gawk glibc gpg2 grep grub2-x86_64-efi gzip hardlink info insserv-compat iputils kmod-compat krb5-mini libacl1 libadns1 libaio1 libapparmor1 libasm1 libassuan0 libattr1 libaudit1 libaugeas0 libblkid1 libbz2-1 libcap-ng0 libcap2 libcom_err2 libcrack2 libcryptsetup4 libcurl4 libdbus-1-3 libdw1 libelf1 libexpat1 libffi4 libfipscheck1 libgcc_s1 libgcrypt20 libgmp10 libgpg-error0 libidn11 libkeyutils1 libkmod2 libksba8 libldap-2_4-2 liblua5_1 liblzma5 libmagic1 libmodman1 libmount1 libncurses5 libopenssl1_0_0 libp11-kit0 libpcre1 libpopt0 libprocps3 libproxy1 libpth20 libqrencode3 libreadline6 libsasl2-3 libseccomp2 libselinux1 libsemanage1 libsepol1 libsgutils2-2 libsmartcols1 libsolv-tools libssh2-1 libstdc++6 libtasn1 libtasn1-6 libudev1 libusb-0_1-4 libusb-1_0-0 libustr-1_0-1 libutempter0 libuuid1 libwrap0 libxml2-2 libz1 libzio1 libzypp netcfg openSUSE-build-key openSUSE-release openSUSE-release-mini openssl p11-kit p11-kit-tools pam pam-config perl-base permissions pigz procps rpm sed shadow suse-module-tools systemd systemd-presets-branding-openSUSE sysvinit-tools terminfo-base update-alternatives util-linux xz zypper
Package 'openSUSE-release-mini' not found.
Jan-29 12:02:43 <3> : Base initialization failed                                                                                                                                                                                    failed
Jan-29 12:02:43 <1> : Closing session with ecode: 1
Jan-29 12:02:43 <3> : KIWI exited with error(s)
Jan-29 12:02:43 <1> : Complete logfile at: /tmp/kiwi/build/image-root.log
```
----------------------snip------------------------
