### ISSUE TITLE
docker inspection gives: "Driver btrfs failed to remove root filesystem"

### ISSUE THREAD

**Issue by cbosdo** [SUSE/machinery#1930]
On a registered SLES 12 SP1, following the first step of the [docker to VM migration page][0] with a build of [this repo (tweaked)][1], machinery fails with an error like the following one:

> Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
> Execution of "docker rm -f 10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720" failed with status 1: > Error response from daemon: Driver btrfs failed to remove root filesystem 10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720: Failed to destroy > btrfs snapshot /var/lib/docker/btrfs/subvolumes for 10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720: device or resource busy (...).
>
> Error output:
> Error response from daemon: Driver btrfs failed to remove root filesystem 10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for 10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720: device or resource busy
> Error: failed to remove containers: [10042cd7b125285cd1f01c9a409ad828cf228c510f951b2d4eeee95b10c90720]
> 
> Backtrace:
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/logged_cheetah.rb:23:in `run`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/docker_system.rb:39:in `stop`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/cli.rb:649:in `block (2 levels) in <class:Cli>`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run`
> /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bin/machinery:33:in `<top (required)>`
> /usr/bin/machinery:24:in `load`
> /usr/bin/machinery:24:in `<main>`

After that, there is no container left in `docker ps -a`, but there the mentioned folder and btrfs snapshot are is present in `/var/lib/docker/btrfs/subvolumes`

[0]:  https://github.com/SUSE/machinery/wiki/Migrate-docker-container-to-to-a-VM
[1]: https://github.com/cledorze/simple-suse-docker

**Comment by cornelius** [comment]
We need to validate this, but let's not use the special label for it.
