### ISSUE TITLE
machinery run from git crashes when go is missing

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#1959]
```
./bin/machinery --version
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.5.0/lib/cheetah.rb:641:in `check_errors': Execution of "rake build" failed with status 1: Warning: The Go compiler is not available on this system. Skipping building the machinery-helper. (...). (Cheetah::ExecutionFailed)
        from /usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.5.0/lib/cheetah.rb:404:in `run'
        from ./bin/machinery:25:in `block in <main>'
        from ./bin/machinery:24:in `chdir'
        from ./bin/machinery:24:in `<main>'
```

**Comment by mauromorales** [comment]
duplicate from #1605 but closing the previous one since this was referenced by the PR
