### ISSUE TITLE
machinery analyze - exception for package "grub2-2.02~beta2"

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#2001]
Acceptance testing for current SLES release (1.18.0):
Inspecting a Leap system, and perform machinery analyze will fail for package "grub2-2.02~beta2".

```
# machinery analyze skylab.suse.de
Setting up repository access...
Generating diffs...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "zypper --non-interactive --no-gpg-checks --root /tmp/machinery_zypper20160303-4356-1bxbod0 -x download grub2-2.02\~beta2" failed with status 4 (no error output).

Standard output:
<?xml version='1.0'?>
<stream>
<message type="error">Error building the cache:
[repo-debug-non-oss|http://download.opensuse.org/debug/distribution/leap/42.1/repo/non-oss/] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;repo-debug-non-oss&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;repo-debug-non-oss&apos;.</message>
<message type="error">Error building the cache:
[repo-debug-update-non-oss|http://download.opensuse.org/debug/update/leap/42.1/non-oss/] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;repo-debug-update-non-oss&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;repo-debug-update-non-oss&apos;.</message>
<message type="error">Some of the repositories have not been refreshed because of an error.</message>
<message type="info">Loading repository data...</message>
<message type="info">Reading installed packages...</message>
<message type="info">Retrieving package grub2-2.02~beta2-76.1.x86_64 (1/1),   2.4 MiB ( 19.8 MiB unpacked)</message>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="0"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="1"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="12"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="23"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="41"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="52"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="63"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="78"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="91"/>
<progress id="" name="(1/1) grub2-2.02~beta2-76.1.x86_64 (download.opensuse.org-oss_1)" value="100"/>
<progress id="" name="(1/1) /tmp/machinery_zypper20160303-4356-1bxbod0/var/cache/zypp/packages/download.opensuse.org-oss_1/x86_64/grub2-2.02~beta2-76.1.x86_64.rpm" value="100"/>
<progress id="" name="(1/1) /tmp/machinery_zypper20160303-4356-1bxbod0/var/cache/zypp/packages/download.opensuse.org-oss_1/x86_64/grub2-2.02~beta2-76.1.x86_64.rpm" done="0"/>
<download-result><solvable><kind>package</kind><name>grub2</name><edition epoch="0" version="2.02~beta2" release="76.1"/><arch>x86_64</arch><repository name="download.opensuse.org-oss_1" alias="download.opensuse.org-oss_1"/></solvable><localfile path="/tmp/machinery_zypper20160303-4356-1bxbod0/var/cache/zypp/packages/download.opensuse.org-oss_1/x86_64/grub2-2.02~beta2-76.1.x86_64.rpm"/></download-result><message type="info">download: Done.</message>
</stream>


Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:97:in `block in call_zypper'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/helper.rb:69:in `with_env'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:96:in `call_zypper'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:77:in `download_package'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:49:in `block (2 levels) in analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:48:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:48:in `block in analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:150:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:150:in `block in with_repositories'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:43:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:43:in `block in isolated'
/usr/lib64/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:30:in `isolated'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:117:in `with_repositories'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:38:in `analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/cli.rb:289:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bin/machinery:33:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
```

**Comment by mauromorales** [comment]
@svollath, @thardeck  could not reproduce ... was the grub2 package installed in a different way?

**Comment by thardeck** [comment]
I could also not reproduce it either, maybe the package could not been downloaded for whatever reason.

The backtrace during failed package downloads is something we should definitely fix though.

**Comment by svollath** [comment]
Actually the package is downloaded. The error seems to be related just to the repo data (e.g. also repo-debug-non-oss).
```
<message type="error">Error building the cache:
[repo-debug-non-oss|http://download.opensuse.org/debug/distribution/leap/42.1/repo/non-oss/] Valid metadata not found at specified URL
```
Which is about the data from "/tmp/machinery_zypper<temporary>".

Here's a list of the repos for that specific Leap installation:
```
# zypper lr -u
#  | Alias                           | Name                                    | Enabled | GPG Check | Refresh | URI                                                                           
---+---------------------------------+-----------------------------------------+---------+-----------+---------+-------------------------------------------------------------------------------
 1 | FATE                            | FATE                                    | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/repositories/FATE/openSUSE_42.1/                 
 2 | download.nvidia.com-leap        | nVidia Graphics Drivers                 | Yes     | (r ) Yes  | Yes     | http://download.nvidia.com/opensuse/leap/42.1                                 
 3 | download.opensuse.org-non-oss   | Main Repository (NON-OSS)               | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.1/repo/non-oss/             
 4 | download.opensuse.org-non-oss_1 | Update Repository (Non-Oss)             | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.1/non-oss/                        
 5 | download.opensuse.org-oss       | Main Repository (OSS)                   | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.1/repo/oss/                 
 6 | download.opensuse.org-oss_1     | Main Update Repository                  | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.1/oss                             
 7 | linuxdownload.adobe.com-linux   | Adobe Flash Plugin                      | Yes     | ( p) Yes  | Yes     | http://linuxdownload.adobe.com/linux/x86_64/                                  
 8 | openSUSE-42.1-0                 | openSUSE-42.1-0                         | Yes     | (r ) Yes  | No      | cd:///?devices=/dev/disk/by-id/ata-PLDS_DVD+_-RW_DS-8ABSH_9F42J7363951E64LOA03
 9 | packman.inode.at-suse           | Packman Repository                      | Yes     | (r ) Yes  | Yes     | http://packman.inode.at/suse/openSUSE_Leap_42.1/                              
10 | repo-debug                      | openSUSE-Leap-42.1-Debug                | No      | ----      | Yes     | http://download.opensuse.org/debug/distribution/leap/42.1/repo/oss/           
11 | repo-debug-non-oss              | openSUSE-Leap-42.1-Debug-Non-Oss        | No      | ----      | Yes     | http://download.opensuse.org/debug/distribution/leap/42.1/repo/non-oss/       
12 | repo-debug-update               | openSUSE-Leap-42.1-Update-Debug         | No      | ----      | Yes     | http://download.opensuse.org/debug/update/leap/42.1/oss                       
13 | repo-debug-update-non-oss       | openSUSE-Leap-42.1-Update-Debug-Non-Oss | No      | ----      | Yes     | http://download.opensuse.org/debug/update/leap/42.1/non-oss/                  
14 | repo-source                     | openSUSE-Leap-42.1-Source               | No      | ----      | Yes     | http://download.opensuse.org/source/distribution/leap/42.1/repo/oss/          
15 | repo-update                     | openSUSE-Leap-42.1-Update               | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.1/oss/
```
