### ISSUE TITLE
Integrations tests setup fails

### ISSUE THREAD

**Issue by vladshablinsky** [SUSE/machinery#2017]
Hi, I'm trying to follow the documentation on integration tests setup and can't make it work.

A little note here: I think the sequence of the options described in `machinery/docs/Integration/Test-Setup.md` is wrong:

```
➜ vlad:git$ pennyworth/bin/pennyworth build-base --definitions-dir=~/Projects/git/machinery/spec/definitions
Unknown option --definitions-dir=~/Projects/git/machinery/spec/definitions

NAME
    build-base - Build base images

SYNOPSIS
    pennyworth [global options] build-base [command options] [IMAGE_NAME]

DESCRIPTION
    Build base images used by Vagrant. If no specific name is given all base
    images are built. The images have to be imported with `import-base` to be
    available to be run. 

COMMAND OPTIONS
    --temp_dir, -t TMP-Dir - Temporary directory for building the Vagrant box.
                             (default: none)

```

When I change the sequence it works but fails:

```
➜ vlad:git$ pennyworth/bin/pennyworth --definitions-dir=~/Projects/git/machinery/spec/definitions build-base
Creating base images...

--- base_opensuse13.1_kvm ---
  Sources not changed, skipping build

--- base_opensuse13.2_kvm ---
  Building base image...
    The build log is available under /tmp/pennyworth-builds/kiwi-terminal-output.log
Pennyworth experienced an unexpected error. Please file a bug report at https://github.com/SUSE/pennyworth/issues/new.
/home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:92:in `rescue in build_kiwi': Execution of "sudo /usr/sbin/kiwi --build /home/vlad/Projects/git/machinery/spec/definitions/boxes/definitions/base_opensuse13.2_kvm --destdir /tmp/pennyworth-builds --logfile /tmp/pennyworth-builds/kiwi-terminal-output.log" failed with status 1 (no error output). (Pennyworth::ExecutionFailed)
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:87:in `build_kiwi'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:60:in `base_image_create'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:41:in `block (2 levels) in execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:32:in `chdir'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:32:in `block in execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:31:in `each'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:31:in `execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/cli.rb:150:in `block (2 levels) in <class:Cli>'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from pennyworth/bin/pennyworth:25:in `<main>'
```

Here is my system configuration:

```
➜ vlad:git$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
➜ vlad:git$ gem -v
2.6.2
➜ vlad:git$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
➜ vlad:git$ bundler -v
Bundler version 1.11.2
➜ vlad:git$ lsb_release -d
Description:	openSUSE 13.2 (Harlequin) (x86_64)
```
How do I solve the problem? Sorry if it's pennywoth's issue, but options are still not  in the right order. Thanks!

**Comment by thardeck** [comment]
Hi @vladshablinsky,

have you looked at `/tmp/pennyworth-builds/kiwi-terminal-output.log`. This normally points you at the bottom to missing packages or issues.
Do you have the packages `kiwi` and `kiwi-desc-vmxboot` installed?

To build Tumbleweed you also will need a newer Kiwi version than the one in 13.2. You can get it from http://download.opensuse.org/repositories/Virtualization:/Appliances/openSUSE_13.2/ .

If you can not make it work let me know and we can use Freenode IRC or something similar to get this working.

**Comment by vladshablinsky** [comment]
@thardeck 
Yes, I had `kiwi-desc-vmxboot`, but I still needed to upgraded it as you said.
Upgrading `kiwi` helped to move a bit further, but I still get errors. It's also strange that creating images fails at first, but when I run the command once again, it can succeed. But the last error I get fails anyway.

``` 
vlad:git$ pennyworth/bin/pennyworth --definitions-dir=~/Projects/git/machinery/spec/definitions build-base
Creating base images...

--- base_opensuse13.1_kvm ---
  Sources not changed, skipping build

--- base_opensuse13.2_kvm ---
  Sources not changed, skipping build

--- base_opensuse_leap_kvm ---
  Sources not changed, skipping build

--- base_opensuse_tumbleweed_kvm ---
  Sources not changed, skipping build

--- base_ubuntu14.04_kvm ---
  Building base image...
Pennyworth experienced an unexpected error. Please file a bug report at https://github.com/SUSE/pennyworth/issues/new.
/home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:79:in `rescue in build_veewee': Execution of "bundle exec veewee kvm build base_ubuntu14.04_kvm --force --auto" failed with status 1:  (...). (Pennyworth::ExecutionFailed)
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:70:in `build_veewee'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:62:in `base_image_create'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:41:in `block (2 levels) in execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:32:in `chdir'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:32:in `block in execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:31:in `each'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/commands/build_base_command.rb:31:in `execute'
	from /home/vlad/Projects/git/pennyworth/lib/pennyworth/cli.rb:150:in `block (2 levels) in <class:Cli>'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /home/vlad/.rvm/gems/ruby-2.3.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from pennyworth/bin/pennyworth:25:in `<main>'
```

**Comment by thardeck** [comment]
@vladshablinsky 
Hey, thx for the quick feedback. Do you have `veewee` installed? `sudo gem install veewee`

It looks like it is missing from the gemspec. I will fix it if it is not installed on your machine.

**Comment by vladshablinsky** [comment]
@thardeck hm, I have this gem installed, reinstalling doesn't change anything, so I get the same error.

**Comment by thardeck** [comment]
The image could not be built because Veewee requires KVM and the system had no vt-x support.
