### ISSUE TITLE
Unexpected error for future format versions (Unknown properties:*)

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#2021]
About the need for integrating extended format version tests ...

I added an unknown property "has_rocketscience", counted up the format version by 1 for a manifest.json and ran "machinery list" with current master (1.18+):

```
...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/array.rb:51:in `initialize': Unknown properties: has_rocketscience (RuntimeError)
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/array.rb:36:in `new'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/array.rb:36:in `from_json'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/scope.rb:38:in `block in for'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/scope.rb:36:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/scope.rb:36:in `for'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:129:in `block in create_scopes'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:121:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:121:in `map'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:121:in `create_scopes'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:117:in `initialize'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:92:in `new'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:92:in `from_hash'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/system_description.rb:67:in `load'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/list_task.rb:32:in `block in list'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/list_task.rb:30:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/list_task.rb:30:in `list'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/lib/cli.rb:717:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5/bin/machinery:41:in `<top (required)>'
	from /usr/bin/machinery:24:in `load'
	from /usr/bin/machinery:24:in `<main>'
```

Modifications to manifest.json:
```
...
  "unmanaged_files": {
    "_attributes": {
      "extracted": false,
      "has_rocketscience": true
    },
...
  "meta": {
    "format_version": 9,
    "unmanaged_files": {
      "modified": "2015-07-31T13:44:21Z",
      "hostname": "g130"
    },
...
```
```
# machinery --version
machinery version 1.18.0.20160315T115832ZopenSUSELeap421git31ba7c5 (system description format version 8)
```

**Comment by svollath** [comment]
In addition it only seems to fail within ```"_attributes": {}``` (unknown one).
