### ISSUE TITLE
machinery breaks when ssh error

### ISSUE THREAD

**Issue by jubalh** [SUSE/machinery#2090]
Independend of machinery: sometimes when connecting to my machine I get an: `ssh_exchange_identification: read: Connection reset by peer`.

If I run machinery and its one of those times then machinery crashes:

```
$: machinery inspect homeserver -n home-now -x --remote-user myname-
Inspecting homeserver for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
 -> Inspection failed!
Inspecting packages...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh myname@myhomeserver.de -o LogLevel\=ERROR LANGUAGE\= LC_ALL\=en_US.utf8 rpm -qa --qf \\\%\\\{NAME\\\}\\\|\\\%\\\{VERSION\\\}\\\|\\\%\\\{RELEASE\\\}\\\|\\\%\\\{ARCH\\\}\\\|\\\%\\\.VENDOR\\\}\\\|\\\%\\\{SIGMD5\\\}\\\$" failed with status 255: ssh_exchange_identification: read: Connection reset by peer

Error output:
ssh_exchange_identification: read: Connection reset by peer

Backtrace:
/usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/remote_system.rb:92:in `run_command'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/plugins/packages/packages_inspector.rb:46:in `inspect_rpm'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/plugins/packages/packages_inspector.rb:29:in `inspect'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/inspect_task.rb:87:in `block in build_description'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/inspect_task.rb:79:in `each'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/inspect_task.rb:79:in `build_description'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/inspect_task.rb:21:in `inspect_system'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/lib/cli.rb:617:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.20.0/bin/machinery:41:in `<top (required)>'
/usr/bin/machinery:23:in `load'
/usr/bin/machinery:23:in `<main>'
```

Probably this should be handled.

Version: 1.20.0

**Comment by mauromorales** [comment]
Thanks @jubalh, we'll have a look into it

**Comment by mostafahussein** [comment]
it might be an issue related to the ssh configuration itself ? maybe there are tcp_wrappers causing the reset of your connection ?

**Comment by jubalh** [comment]
I had configured `hosts.allow` to only allow certain machines. Seems when I tried to log in from work I sometimes got a .us IP (which was not allowed) in this case it didn't accept.

Still I think machinery shouldnt crash here thats why I reported it :)

**Comment by cornelius** [comment]
## Acceptance criteria

* When ssh closes the connection during inspection with an error, the error is reported to the user as `ssh error: <ssh error message>`. In this concrete case it will look like this: `ssh error: ssh_exchange_identification: read: Connection reset by peer`
* There is no backtrace shown

**Comment by cornelius** [comment]
## Tasks

* [ ] Catch exception
* [ ] QA
