### ISSUE TITLE
Unexpected Error for unknown/wrong filter path (--exclude=)

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#2123]
Using this filter, or e.g. also with ```/changed_managed_files/files/name=/var/cache/``` will lead to an unexpected error:
```
# machinery inspect --exclude=/changed_managed_files/files/name=/var/cache/ -n localhost3 localhost
Inspecting localhost for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
 -> Found operating system 'openSUSE Leap' version '42.1'.
Inspecting packages...
 -> Found 2230 packages.
Inspecting patterns...
 -> Found 22 patterns.
Inspecting repositories...
 -> Found 14 repositories.
Inspecting users...
 -> Found 36 users.
Inspecting groups...
 -> Found 61 groups.
Inspecting services...
 -> Found 248 services.
Inspecting changed-config-files...
 -> Found 18 changed configuration files.
Inspecting changed-managed-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/array.rb:187:in `[]': no implicit conversion of String into Integer (TypeError)
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/array.rb:187:in `method_missing'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/filter.rb:151:in `block (2 levels) in apply!'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/filter.rb:149:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/filter.rb:149:in `block in apply!'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/filter.rb:143:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/filter.rb:143:in `apply!'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/inspect_task.rb:96:in `block in build_description'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/inspect_task.rb:79:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/inspect_task.rb:79:in `build_description'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/inspect_task.rb:21:in `inspect_system'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/lib/cli.rb:617:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.21.0.20160705T164338ZopenSUSELeap421git8716c66/bin/machinery:41:in `<top (required)>'
	from /usr/bin/machinery:24:in `load'
	from /usr/bin/machinery:24:in `<main>'
```

**Comment by cornelius** [comment]
#2189 will fix this
