### ISSUE TITLE
Unexpected error in machinery analyze

### ISSUE THREAD

**Issue by nbornstein** [SUSE/machinery#2132]
Error running analyze. SMT repositories are located locally on laptop hard drive, accessed via NFS. 
```
nbornstein@laptop:~> machinery analyze suma3
Setting up repository access...
Generating diffs...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "zypper --non-interactive --no-gpg-checks --root /tmp/machinery_zypper20160810-8292-h0xo1a -x download cobbler-2.6.6" failed with status 106 (no error output).

Standard output:
<?xml version='1.0'?>
<stream>
<message type="error">Failed to mount laptop:/data/repo/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product on /var/tmp/AP_0xHE5i3e: Mounting media failed (mount: only root can use &quot;--options&quot; option)
</message>
<prompt id="8">
<text>Abort, retry, ignore?</text>
<option default="1" value="a" desc="Skip retrieval of the file and abort current operation."/>
<option value="r" desc="Try to retrieve the file again."/>
<option value="i" desc="Skip retrieval of the file and try to continue with the operation without the file."/>
<option value="u" desc="Change current base URI and try retrieving the file again."/>
</prompt>
<message type="error">Error building the cache:
[SLES12-SP1-Pool|nfs://laptop/data/repo/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;SLES12-SP1-Pool&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;SLES12-SP1-Pool&apos;.</message>
<message type="error">Failed to mount laptop:/data/repo/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update on /var/tmp/AP_0xLvPE9F: Mounting media failed (mount: only root can use &quot;--options&quot; option)
</message>
<prompt id="8">
<text>Abort, retry, ignore?</text>
<option default="1" value="a" desc="Skip retrieval of the file and abort current operation."/>
<option value="r" desc="Try to retrieve the file again."/>
<option value="i" desc="Skip retrieval of the file and try to continue with the operation without the file."/>
<option value="u" desc="Change current base URI and try retrieving the file again."/>
</prompt>
<message type="error">Error building the cache:
[SLES12-SP1-Updates|nfs://laptop/data/repo/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;SLES12-SP1-Updates&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;SLES12-SP1-Updates&apos;.</message>
<message type="error">Failed to mount laptop:/data/repo/SUSE/Products/SUSE-Manager-Server/3.0/x86_64/product on /var/tmp/AP_0xSWxpg7: Mounting media failed (mount: only root can use &quot;--options&quot; option)
</message>
<prompt id="8">
<text>Abort, retry, ignore?</text>
<option default="1" value="a" desc="Skip retrieval of the file and abort current operation."/>
<option value="r" desc="Try to retrieve the file again."/>
<option value="i" desc="Skip retrieval of the file and try to continue with the operation without the file."/>
<option value="u" desc="Change current base URI and try retrieving the file again."/>
</prompt>
<message type="error">Error building the cache:
[SUSE-Manager-Server-3.0-Pool|nfs://laptop/data/repo/SUSE/Products/SUSE-Manager-Server/3.0/x86_64/product] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;SUSE-Manager-Server-3.0-Pool&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;SUSE-Manager-Server-3.0-Pool&apos;.</message>
<message type="error">Failed to mount laptop:/data/repo/SUSE/Updates/SUSE-Manager-Server/3.0/x86_64/update on /var/tmp/AP_0xYK9xny: Mounting media failed (mount: only root can use &quot;--options&quot; option)
</message>
<prompt id="8">
<text>Abort, retry, ignore?</text>
<option default="1" value="a" desc="Skip retrieval of the file and abort current operation."/>
<option value="r" desc="Try to retrieve the file again."/>
<option value="i" desc="Skip retrieval of the file and try to continue with the operation without the file."/>
<option value="u" desc="Change current base URI and try retrieving the file again."/>
</prompt>
<message type="error">Error building the cache:
[SUSE-Manager-Server-3.0-Updates|nfs://laptop/data/repo/SUSE/Updates/SUSE-Manager-Server/3.0/x86_64/update] Valid metadata not found at specified URL
</message>
<message type="warning">The metadata cache needs to be built for the &apos;SUSE-Manager-Server-3.0-Updates&apos; repository. You can run &apos;zypper refresh&apos; as root to do this.</message>
<message type="info">Disabling repository &apos;SUSE-Manager-Server-3.0-Updates&apos;.</message>
<message type="error">Some of the repositories have not been refreshed because of an error.</message>
<message type="info">Loading repository data...</message>
<message type="info">Reading installed packages...</message>
<message type="info">Retrieving package cobbler-2.6.6-33.2.noarch (1/1), 449.8 KiB (  2.1 MiB unpacked)</message>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="3"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="14"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="28"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="39"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="53"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="64"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="78"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="92"/>
<progress id="" name="(1/1) cobbler-2.6.6-33.2.noarch (SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates)" value="100"/>
<progress id="" name="(1/1) /tmp/machinery_zypper20160810-8292-h0xo1a/var/cache/zypp/packages/SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates/noarch/cobbler-2.6.6-33.2.noarch.rpm" value="100"/>
<progress id="" name="(1/1) /tmp/machinery_zypper20160810-8292-h0xo1a/var/cache/zypp/packages/SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates/noarch/cobbler-2.6.6-33.2.noarch.rpm" done="0"/>
<download-result><solvable><kind>package</kind><name>cobbler</name><edition epoch="0" version="2.6.6" release="33.2"/><arch>noarch</arch><repository name="SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates" alias="SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates"/></solvable><localfile path="/tmp/machinery_zypper20160810-8292-h0xo1a/var/cache/zypp/packages/SUSE_Manager_Server_3.0_x86_64:SUSE-Manager-Server-3.0-Updates/noarch/cobbler-2.6.6-33.2.noarch.rpm"/></download-result><message type="info">download: Done.</message>
</stream>


Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:97:in `block in call_zypper'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/helper.rb:69:in `with_env'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:96:in `call_zypper'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:77:in `download_package'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:49:in `block (2 levels) in analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:48:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:48:in `block in analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:150:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:150:in `block in with_repositories'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:43:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:43:in `block in isolated'
/usr/lib64/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/zypper.rb:30:in `isolated'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:117:in `with_repositories'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/analyze_config_file_diffs_task.rb:38:in `analyze'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/lib/cli.rb:289:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.18.0/bin/machinery:33:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
```

**Comment by thardeck** [comment]
Hi @nbornstein, thx for reporting the issue. I could reproduce it here locally and we will look into fixing it soon.
