### ISSUE TITLE
machinery-helper failed with status 1 (error output streamed away).

### ISSUE THREAD

**Issue by TheBigBear** [SUSE/machinery#2135]
```
machinery inspect -r machinery.uk --name=cservices cservices
```

returns:

```
Inspecting cservices for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
 -> Inspection failed!
Inspecting packages...
 -> Found 898 packages.
Inspecting patterns...
 -> For a patterns (tasks) inspection please install the package tasksel on the inspected system.
Inspecting repositories...
 -> Found 31 repositories.
Inspecting users...
 -> Found 0 users.
Inspecting groups...
 -> Found 0 groups.
Inspecting services...
 -> Found 104 services.
Inspecting changed-config-files...
 -> Found 0 changed configuration files.
Inspecting changed-managed-files...
 -> Found 0 changed managed files.
Inspecting unmanaged-files...
sudo: sorry, you must have a tty to run sudo

Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh machinery.uk@cservices -o LogLevel\=ERROR sudo -n LANGUAGE\= LC_ALL\=en_US.utf8 /home/machinery.uk/machinery-helper" failed with status 1 (error output streamed away).

Backtrace:
/usr/local/share/gems/gems/cheetah-0.5.0/lib/cheetah.rb:641:in `check_errors'
/usr/local/share/gems/gems/cheetah-0.5.0/lib/cheetah.rb:404:in `run'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/logged_cheetah.rb:23:in `run'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/remote_system.rb:92:in `run_command'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/machinery_helper.rb:60:in `run_helper'
/usr/local/share/gems/gems/machinery-tool-1.21.0/plugins/unmanaged_files/unmanaged_files_inspector.rb:85:in `run_helper_inspection'
/usr/local/share/gems/gems/machinery-tool-1.21.0/plugins/unmanaged_files/unmanaged_files_inspector.rb:59:in `inspect'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/inspect_task.rb:87:in `block in build_description'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/inspect_task.rb:79:in `each'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/inspect_task.rb:79:in `build_description'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/inspect_task.rb:21:in `inspect_system'
/usr/local/share/gems/gems/machinery-tool-1.21.0/lib/cli.rb:617:in `block (2 levels) in <class:Cli>'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `call'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `execute'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/app_support.rb:296:in `block in call_command'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call_command'
/usr/local/share/gems/gems/gli-2.14.0/lib/gli/app_support.rb:83:in `run'
/usr/local/share/gems/gems/machinery-tool-1.21.0/bin/machinery:41:in `<top (required)>'
/usr/local/bin/machinery:23:in `load'
/usr/local/bin/machinery:23:in `<main>'
```

Any idea, on what I could do to get this resolved?

BTW this is a dedicated RHEL 5.11 server with Plesk 12.5.30 installed and being maintained by Rackspace UK, who use SLES Expanded support to maintain the RHEL machine more cheaply that using the original RHEL repos.
 

```ls /etc/*release```
```
/etc/centos-release  /etc/redhat-release
/etc/plesk-release   /etc/system-release
```

```cat /etc/centos-release```

```
Red Hat Enterprise Linux Server release 5.11 (Tikanga)
# This is a "SLES Expanded Support platform release 5.11"
# The above "Red Hat Enterprise Linux Server" string is only used to 
# keep software compatibility.
```

```cat /etc/redhat-release```
``` 
Red Hat Enterprise Linux Server release 5.11 (Tikanga)
# This is a "SLES Expanded Support platform release 5.11"
# The above "Red Hat Enterprise Linux Server" string is only used to 
# keep software compatibility.
```

```cat /etc/plesk-release``` 
```
12.5.30 rhel5.build1205150826.19
```

```cat /etc/system-release```
```
Red Hat Enterprise Linux Server release 5.11 (Tikanga)
# This is a "SLES Expanded Support platform release 5.11"
# The above "Red Hat Enterprise Linux Server" string is only used to 
# keep software compatibility.
```

**Comment by thardeck** [comment]
Hi @TheBigBear, thx for reporting the issue.

The reason for this issue is the same as for issue #2137. So the workaround should help there too.

**Comment by thardeck** [comment]
In the latest release 1.22.1, the case is handled, by showing an error message how to fix the issue.
