### ISSUE TITLE
error running machinery

### ISSUE THREAD

**Issue by cclark64** [SUSE/machinery#2263]
usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:53:in `block in parse_groups': undefined method `split' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:42:in `map'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:42:in `parse_groups'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:30:in `inspect'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:87:in `block in build_description'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:79:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:79:in `build_description'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:21:in `inspect_system'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/lib/cli.rb:768:in `block (2 levels) in <class:Cli>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gli-2.18.0/lib/gli/command_support.rb:131:in `execute'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gli-2.18.0/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gli-2.18.0/lib/gli/app_support.rb:309:in `call_command'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gli-2.18.0/lib/gli/app_support.rb:83:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/machinery-tool-1.23.1/bin/machinery:41:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/machinery:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/machinery:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:24:in `<main>'

**Comment by thardeck** [comment]
Thanks for your report. The issue sounds related to #2261.
Did you edit your `/etc/group` manually or can you check if your file got similar issues?

Does the issue also appear, if you do not inspect groups `machinery inspect -e groups `?
