### ISSUE TITLE
TW -> Leap 15.2 remote scan fails with glibc error

### ISSUE THREAD

**Issue by zoopla-jb** [SUSE/machinery#2285]
Host OS:  Tumbleweed
machinery Version        : 1.24.1-1.10

```
aaa@bbb:~/Documents/machinery> machinery inspect --extract-files -raaa --name=test example.com
Inspecting example.com for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
-> Found operating system 'openSUSE Leap' version '15.2'.
Inspecting packages...
-> Found 497 packages.
Inspecting patterns...
-> Found 1 pattern.
Inspecting repositories...
-> Found 14 repositories.
Inspecting users...
-> Found 23 users.
Inspecting groups...
-> Found 40 groups.
Inspecting services...
-> Found 149 services.
Inspecting changed-config-files...
-> Inspection failed!
Inspecting changed-managed-files...
-> Inspection failed!
Inspecting unmanaged-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh aaa@example.com -o LogLevel\=ERROR LANGUAGE\= LC_ALL\=en_US.utf8 /home/aaa/machinery-helper --version" failed with status 1: /home/aaa/machinery-helper: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/aaa/machinery-helper).

Error output:
/home/aaa/machinery-helper: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/aaa/machinery-helper)

Backtrace:
/usr/lib64/ruby/gems/2.7.0/gems/cheetah-0.5.2/lib/cheetah.rb:670:in `check_errors'
/usr/lib64/ruby/gems/2.7.0/gems/cheetah-0.5.2/lib/cheetah.rb:410:in `run'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/remote_system.rb:98:in `run_command'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/machinery_helper.rb:79:in `has_compatible_version?'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/plugins/unmanaged_files/unmanaged_files_inspector.rb:77:in `run_helper_inspection'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/plugins/unmanaged_files/unmanaged_files_inspector.rb:60:in `inspect'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/inspect_task.rb:87:in `block in build_description'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/inspect_task.rb:79:in `each'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/inspect_task.rb:79:in `build_description'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/inspect_task.rb:21:in `inspect_system'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/lib/cli.rb:768:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.7.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.7.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.7.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.7.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
/usr/lib64/ruby/gems/2.7.0/gems/machinery-tool-1.24.1/bin/machinery:41:in `<top (required)>'
/usr/bin/machinery:23:in `load'
/usr/bin/machinery:23:in `<main>'
```

**Comment by zoopla-jb** [comment]
Ah this is a build issue due to it being removed from factory. https://build.opensuse.org/package/show/systemsmanagement:machinery/machinery but not removed from repo.

Can we expect the build to be fixed and resubmitted?
