### ISSUE TITLE
machinery show crashes when piped to less

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#521]
`machinery show` crashes when piped to `less` and exited by hitting `q`.

```
# machinery show kona  | less
Machinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/ui.rb:63:in `write': Broken pipe - <STDOUT> (Errno::EPIPE)
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/ui.rb:63:in `puts'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/ui.rb:63:in `puts'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/ui.rb:37:in `print_output'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/show_task.rb:63:in `show_console'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/show_task.rb:23:in `show'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/lib/cli.rb:558:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.2.0.20150113T104335ZopenSUSE131git7860688/bin/machinery:26:in `<top (required)>'
        from /usr/bin/machinery:26:in `load'
        from /usr/bin/machinery:26:in `<main>'
```

**Comment by thardeck** [comment]
I am unable to reproduce this on 13.2

**Comment by ajaeger** [comment]
I can still reproduce it.

**Comment by thardeck** [comment]
The issue seems to only appear if the system description output isn't small.

**Comment by vwallfahrer** [comment]
It also crashes by using 

```
machinery show --no-pager sles12 | less

```
that means the problem is not the double usage of less.
