### ISSUE TITLE
Machinery "JSON error" parser fails with simple broken json

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#584]
Try to load a manifest.json which looks like this:
```
{broken}
```
     Failure/Error: list_task.list(store)
     ArgumentError:
       bad value for range
     # ./lib/manifest.rb:77:in `rescue in parse'
     # ./lib/manifest.rb:69:in `parse'
     # ./lib/manifest.rb:40:in `initialize'
     # ./lib/manifest.rb:32:in `new'
     # ./lib/manifest.rb:32:in `load'
     # ./lib/list_task.rb:31:in `block in list'
     # ./lib/list_task.rb:28:in `each'
     # ./lib/list_task.rb:28:in `list'
     # ./spec/unit/list_task_spec.rb:100:in `block (3 levels) in <top (required)>'

**Comment by thardeck** [comment]
It seems that our own error parser fails there.
