### ISSUE TITLE
Unmanaged-File inspector crashed with 'extract_tar_metadata': undefined method `user=' for nil:NilClass (NoMethodError)'

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#632]
I inspected a test host (albinoni) which had openSUSE 13.2 installed and ran into an unexpected unmanaged-file inspector issue.
```
Inspecting unmanaged-files...
The content of the following remote directories is ignored: /mounts, /suse.
The content of the following special directories is ignored: /sys, /proc, /dev, /dev/shm, /run, /sys/fs/cgroup, /var/lib/ntp/proc.
Machinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:119:in `block (2 levels) in extract_tar_metadata': undefined method `user=' for nil:NilClass (NoMethodError)
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:114:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:114:in `block in extract_tar_metadata'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:111:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:111:in `extract_tar_metadata'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/plugins/inspect/unmanaged_files_inspector.rb:380:in `inspect'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/lib/inspect_task.rb:78:in `block in build_description'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/lib/inspect_task.rb:75:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/lib/inspect_task.rb:75:in `build_description'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/lib/inspect_task.rb:23:in `inspect_system'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/lib/cli.rb:459:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.4.0/bin/machinery:26:in `<top (required)>'
        from /usr/bin/machinery:26:in `load'
        from /usr/bin/machinery:26:in `<main>'
```

**Comment by thardeck** [comment]
I can be reproduced by creating a file with many spaces in it:
`touch "/etc/zypp/repos.d/http-download.opensuse.org-c210201b                       .repo"`

**Comment by thardeck** [comment]
The problem is the tarball parsing with "tar -tvf <file>" which filters the spaces.
