### ISSUE TITLE
Error when filter file does not exist

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#676]
If you run `machinery inspect --skip-files=@~/jdfhjksdfh` you get an unexpected error:

```
Machinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.4.0.20150309T155224ZopenSUSE131gitbfc420c/lib/cli.rb:660:in `read': No such file or directory - ~/machinery-filters.txt (Errno::ENOENT)
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.4.0.20150309T155224ZopenSUSE131gitbfc420c/lib/cli.rb:660:in `block in prepare_filter'
```
It should instead show a nice error message that the file couldn't be found.

**Comment by cornelius** [comment]
The error message is one problem. That the `~` is not expanded is another one.
