### ISSUE TITLE
excluding comma separated values crashes machinery

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#735]
```
./bin/machinery --exclude='/services/services/state=enabled,disabled' inspect --scope services 192.168.121.229
Inspecting 192.168.121.229 for services...
Inspecting services...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/src/chuller/machinery/lib/element_filter.rb:38:in `block in matches?': undefined method `elements' for "static":String (NoMethodError)
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `each'
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `matches?'
	from /usr/src/chuller/machinery/lib/filter.rb:138:in `block (2 levels) in apply!'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `delete_if'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `method_missing'
	from /usr/src/chuller/machinery/lib/filter.rb:137:in `block in apply!'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `each'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `apply!'
	from /usr/src/chuller/machinery/lib/system_description.rb:209:in `set_filter'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:107:in `block in build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `each'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/src/chuller/machinery/lib/cli.rb:474:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from ./bin/machinery:28:in `<main>'
```

Documentation on the filters page explicitly mentions comma separation as a method to filter several elements

**Comment by greygoo** [comment]
also breaks with double quotes (as used and descripbed in the wiki):

```
./bin/machinery --exclude="/services/services/state=enabled,disabled" inspect --scope services 192.168.121.229
```
