### ISSUE TITLE
filtering array of users in a inspected group throws error

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#741]
I added some users to the group users in /etc/group and then inspected the system. This gives me an entry in manifest.json looking like this:

```
    {
      "name": "users",
      "password": "x",
      "gid": 100,
      "users": [
        "root",
        "vagrant",
        "uucp"
      ]
    }
```

now when I try to filter out this group based on the users in it - which are an array - I should be able to do so with 

```
./bin/machinery --exclude="/groups/users=root,vagrant,uucp"  inspect --scope groups 192.168.121.229
```

however, that throws the following error:

```
Inspecting 192.168.121.229 for groups...
Inspecting groups...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/src/chuller/machinery/lib/element_filter.rb:38:in `block in matches?': undefined method `elements' for []:Array (NoMethodError)
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `each'
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `matches?'
	from /usr/src/chuller/machinery/lib/filter.rb:138:in `block (2 levels) in apply!'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `delete_if'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `method_missing'
	from /usr/src/chuller/machinery/lib/filter.rb:137:in `block in apply!'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `each'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `apply!'
	from /usr/src/chuller/machinery/lib/system_description.rb:209:in `set_filter'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:107:in `block in build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `each'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/src/chuller/machinery/lib/cli.rb:474:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from ./bin/machinery:28:in `<main>'
```

**Comment by greygoo** [comment]
Happens as well for other scopes:

----------------snip------------------
 ./bin/machinery  --exclude="/changed_managed_files/files/changes=size,md5" inspect --scope changed-managed-files 192.168.121.229
Inspecting 192.168.121.229 for changed-managed-files...
Inspecting changed-managed-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/src/chuller/machinery/lib/element_filter.rb:38:in `block in matches?': undefined method `elements' for ["size", "md5"]:Array (NoMethodError)
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `each'
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `matches?'
	from /usr/src/chuller/machinery/lib/filter.rb:138:in `block (2 levels) in apply!'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `delete_if'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `method_missing'
	from /usr/src/chuller/machinery/lib/filter.rb:137:in `block in apply!'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `each'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `apply!'
	from /usr/src/chuller/machinery/lib/system_description.rb:209:in `set_filter'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:107:in `block in build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `each'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/src/chuller/machinery/lib/cli.rb:474:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from ./bin/machinery:28:in `<main>'
----------------snip------------------

**Comment by greygoo** [comment]
If I run the exact command from the documentation it also fails: 
```
./bin/machinery  --exclude="/changed_managed_files/files/changes=mode,user" inspect --scope changed-managed-files 192.168.121.229
Inspecting 192.168.121.229 for changed-managed-files...
Inspecting changed-managed-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/src/chuller/machinery/lib/element_filter.rb:38:in `block in matches?': undefined method `elements' for ["size", "md5"]:Array (NoMethodError)
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `each'
	from /usr/src/chuller/machinery/lib/element_filter.rb:35:in `matches?'
	from /usr/src/chuller/machinery/lib/filter.rb:138:in `block (2 levels) in apply!'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `delete_if'
	from /usr/src/chuller/machinery/lib/array.rb:91:in `method_missing'
	from /usr/src/chuller/machinery/lib/filter.rb:137:in `block in apply!'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `each'
	from /usr/src/chuller/machinery/lib/filter.rb:123:in `apply!'
	from /usr/src/chuller/machinery/lib/system_description.rb:209:in `set_filter'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:107:in `block in build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `each'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:92:in `build_description'
	from /usr/src/chuller/machinery/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/src/chuller/machinery/lib/cli.rb:474:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from ./bin/machinery:28:in `<main>'
```

the error does not point to the given arrray values but the first entry in manifest.json:

```
  "changed_managed_files": {
    "extracted": false,
    "files": [
      {
        "name": "/usr/share/info/sed.info.gz",
        "package_name": "sed",
        "package_version": "4.2.2",
        "status": "changed",
        "changes": [
          "size",
          "md5"
        ]
...
```

**Comment by greygoo** [comment]
tested and fixed

**Comment by greygoo** [comment]
reopening until fix is in master
