### ISSUE TITLE
Errors when inspecting unmanaged files with Tumbleweed

### ISSUE THREAD

**Issue by boblmartens** [SUSE/machinery#883]
I get the following error while inspecting my Tumbleweed system with `machinery inspect localhost`

```
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `exec': no implicit conversion of Fixnum into String (TypeError)
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:461:in `block in fork_commands_recursive'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:425:in `fork_commands_recursive'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:471:in `fork_commands'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/cheetah-0.4.0/lib/cheetah.rb:359:in `run'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/local_system.rb:88:in `block in run_command'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/helper.rb:47:in `with_env'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/helper.rb:37:in `with_c_locale'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/local_system.rb:87:in `run_command'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/plugins/unmanaged_files/unmanaged_files_inspector.rb:153:in `get_find_data'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/plugins/unmanaged_files/unmanaged_files_inspector.rb:285:in `inspect'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/inspect_task.rb:86:in `block in build_description'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/inspect_task.rb:78:in `each'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/inspect_task.rb:78:in `build_description'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/lib/cli.rb:510:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bundle/ruby/2.2.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.7.0/bin/machinery:28:in `<top (required)>'
	from /usr/bin/machinery:26:in `load'
	from /usr/bin/machinery:26:in `<main>'
```

Any help would be greatly appreciated. Thanks!

**Comment by boblmartens** [comment]
This issue does not arise when inspecting a remote host.

**Comment by tgoettlicher** [comment]
Thank you for reporting this issue.

That's the fix: https://github.com/SUSE/machinery/commit/76261d47fa8869e9244d8547cf79e99210eb2530

**Comment by boblmartens** [comment]
Thanks you greatly for the work!

**Comment by tgoettlicher** [comment]
Closing this issue.
