### ISSUE TITLE
Permission denied while inspecting repositories with sudo

### ISSUE THREAD

**Issue by gsanso** [SUSE/machinery#922]
Permission denied while inspecting repositories with sudo

```
peon@dhcp150:~> machinery inspect -n SLES12 10.100.103.110 --remote-user=alfred
Inspecting 10.100.103.110 for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
 -> Found operating system 'SUSE Linux Enterprise Server 12' version '12'.
Inspecting packages...
 -> Found 919 packages.
Inspecting patterns...
 -> Found 9 patterns.
Inspecting repositories...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh alfred@10.100.103.110 LC_ALL\=C cat /etc/zypp/credentials.d/SCCcredentials" failed with status 1: cat: /etc/zypp/credentials.d/SCCcredentials: Permission denied.

Error output:
cat: /etc/zypp/credentials.d/SCCcredentials: Permission denied

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/logged_cheetah.rb:24:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/helper.rb:55:in `with_env'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/helper.rb:45:in `with_c_locale'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/remote_system.rb:77:in `run_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/plugins/repositories/repositories_inspector.rb:115:in `block in get_credentials_from_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/plugins/repositories/repositories_inspector.rb:114:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/plugins/repositories/repositories_inspector.rb:114:in `get_credentials_from_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/plugins/repositories/repositories_inspector.rb:65:in `inspect_zypp_repositories'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/plugins/repositories/repositories_inspector.rb:27:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/inspect_task.rb:86:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/inspect_task.rb:78:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/inspect_task.rb:78:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/inspect_task.rb:23:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/lib/cli.rb:513:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.1/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:26:in `load'
/usr/bin/machinery:26:in `<main>'
```

**Comment by gsanso** [comment]
This was fixed in https://github.com/SUSE/machinery/pull/918
